name: Build Windows VS

# The caller is responsible for making sure all options passed to this workflow are valid and compatible with each other.

on:
  workflow_call:
    inputs:
      ref:
        required: false
        default: ''
        type: string
      config:
        required: false
        default: 'Release'
        type: string
        # options:
        #   - Debug
        #   - Release
      plat:
        required: false
        type: string
        default: 'winkernel'
        # options:
        #   - winkernel
        #   - windows
      os:
        required: false
        type: string
        default: 'windows-2019'
        # options:
        #   - windows-2019
        #   - windows-2022
      arch:
        required: false
        default: 'x64'
        type: string
        # options:
        #   - x86
        #   - x64
        #   - arm64

permissions: read-all

jobs:
  build-windows-vs-reuse:
    name: Build
    runs-on: ${{ inputs.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      with:
        repository: microsoft/cxplat
        ref: ${{ inputs.ref }}
        submodules: recursive
    - name: Prepare Machine
      shell: pwsh
      run: scripts/prepare-machine.ps1 -ForBuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce
    - name: Build
      shell: pwsh
      run: scripts/build.ps1 -Config ${{ inputs.config }} -Platform ${{ inputs.plat }} -Arch ${{ inputs.arch }} -BuildToolSet vs
    - name: Sign Kernel
      if: inputs.plat == 'winkernel'
      shell: pwsh
      run: scripts/sign.ps1 -Config ${{ inputs.config }} -Arch ${{ inputs.arch }}
    - name: Upload build artifacts
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
      with:
        name: ${{ inputs.config }}-${{ inputs.plat }}-${{ inputs.os }}-${{ inputs.arch }}-vs
        path: artifacts
