name: BVT

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*

concurrency:
  # Cancel any workflow currently in progress for the same PR.
  # Allow running concurrently with any other commits.
  group: bvt-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build-windows-kernel:
    name: Build WinKernel
    strategy:
      fail-fast: false
      matrix:
        vec: [
          { config: "Debug", plat: "winkernel", os: "windows-2022", arch: "x64" },
          { config: "Release", plat: "winkernel", os: "windows-2022", arch: "x64" }
        ]
    uses: ./.github/workflows/build-reuse-vs.yml
    with:
      config: ${{ matrix.vec.config }}
      plat: ${{ matrix.vec.plat }}
      os: ${{ matrix.vec.os }}
      arch: ${{ matrix.vec.arch }}

  build-windows:
    name: Build WinUser
    strategy:
      fail-fast: false
      matrix:
        vec: [
          { config: "Debug", plat: "windows", os: "windows-2022", arch: "x64" },
          { config: "Release", plat: "windows", os: "windows-2022", arch: "x64" }
        ]
    uses: ./.github/workflows/build-reuse-win.yml
    with:
      config: ${{ matrix.vec.config }}
      plat: ${{ matrix.vec.plat }}
      os: ${{ matrix.vec.os }}
      arch: ${{ matrix.vec.arch }}

  build-ubuntu:
    name: Build Ubuntu
    strategy:
      fail-fast: false
      matrix:
        vec: [
          { config: "Debug", plat: "linux", os: "ubuntu-20.04", arch: "x64" },
          { config: "Release", plat: "linux", os: "ubuntu-20.04", arch: "x64" },
          { config: "Debug", plat: "linux", os: "ubuntu-22.04", arch: "x64" },
          { config: "Release", plat: "linux", os: "ubuntu-22.04", arch: "x64" }
        ]
    uses: ./.github/workflows/build-reuse-unix.yml
    with:
      config: ${{ matrix.vec.config }}
      plat: ${{ matrix.vec.plat }}
      os: ${{ matrix.vec.os }}
      arch: ${{ matrix.vec.arch }}

  build-macos:
    name: Build MacOs
    strategy:
      fail-fast: false
      matrix:
        vec: [
          { config: "Debug", plat: "macos", os: "macos-12", arch: "x64" },
          { config: "Release", plat: "macos", os: "macos-12", arch: "x64" }
        ]
    uses: ./.github/workflows/build-reuse-unix.yml
    with:
      config: ${{ matrix.vec.config }}
      plat: ${{ matrix.vec.plat }}
      os: ${{ matrix.vec.os }}
      arch: ${{ matrix.vec.arch }}

  bvt:
    name: BVT
    needs: [build-windows, build-ubuntu, build-macos]
    strategy:
      fail-fast: false
      matrix:
        vec: [
          { config: "Debug",   plat: "linux",   os: "ubuntu-20.04", arch: "x64" },
          { config: "Release", plat: "linux",   os: "ubuntu-20.04", arch: "x64" },
          { config: "Debug",   plat: "linux",   os: "ubuntu-22.04", arch: "x64" },
          { config: "Release", plat: "linux",   os: "ubuntu-22.04", arch: "x64" },
          { config: "Debug",   plat: "windows", os: "windows-2019", arch: "x64" },
          { config: "Release", plat: "windows", os: "windows-2019", arch: "x64" },
          { config: "Debug",   plat: "windows", os: "windows-2022", arch: "x64" },
          { config: "Release", plat: "windows", os: "windows-2022", arch: "x64" },
          { config: "Debug",   plat: "macos", os: "macos-12", arch: "x64" },
          { config: "Release", plat: "macos", os: "macos-12", arch: "x64" }
        ]
    runs-on: ${{ matrix.vec.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - name: Download Build Artifacts
      uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
      if: matrix.vec.plat == 'windows'
      with: # note we always use binaries built on windows-2022.
        name: ${{ matrix.vec.config }}-${{ matrix.vec.plat }}-windows-2022-${{ matrix.vec.arch }}
        path: artifacts
    - name: Download Build Artifacts (WinKernel)
      uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
      if: matrix.vec.plat == 'winkernel'
      with: # note we always use binaries built on windows-2022.
        name: ${{ matrix.vec.config }}-${{ matrix.vec.plat }}-windows-2022-${{ matrix.vec.arch }}-vs
        path: artifacts
    - name: Download Build Artifacts
      uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
      if: matrix.vec.plat == 'linux' || matrix.vec.plat == 'macos'
      with:
        name: ${{ matrix.vec.config }}-${{ matrix.vec.plat }}-${{ matrix.vec.os }}-${{ matrix.vec.arch }}-
        path: artifacts
    - name: Fix permissions for Unix
      if: matrix.vec.plat == 'linux' || matrix.vec.plat == 'macos'
      run: sudo chmod -R 777 artifacts
    - name: Prepare Machine
      run: scripts/prepare-machine.ps1 -ForTest
      shell: pwsh
    - name: Test
      if: matrix.vec.os == 'WinServerPrerelease'
      shell: pwsh
      timeout-minutes: 5
      run: scripts/test.ps1 -Config ${{ matrix.vec.config }} -Arch ${{ matrix.vec.arch }} -GHA -GenerateXmlResults
    - name: Test
      if: matrix.vec.os != 'WinServerPrerelease'
      shell: pwsh
      timeout-minutes: 5
      run: scripts/test.ps1 -Config ${{ matrix.vec.config }} -Arch ${{ matrix.vec.arch }} -OsRunner ${{ matrix.vec.os }} -GHA -GenerateXmlResults
    - name: Upload on Failure
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
      if: failure()
      with:
        name: BVT-${{ matrix.vec.config }}-${{ matrix.vec.plat }}-${{ matrix.vec.os }}-${{ matrix.vec.arch }}
        path: artifacts

  bvt-kernel:
    name: BVT Kernel
    needs: [build-windows, build-windows-kernel]
    strategy:
      fail-fast: false
      matrix:
        vec: [
          { config: "Debug",   plat: "winkernel", os: "windows-2022", arch: "x64" },
          { config: "Release", plat: "winkernel", os: "windows-2022", arch: "x64" }
        ]
    runs-on: ${{ matrix.vec.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - name: Download Build Artifacts
      uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
      with: # note we always use binaries built on windows-2022.
        name: ${{ matrix.vec.config }}-${{ matrix.vec.plat }}-windows-2022-${{ matrix.vec.arch }}
        path: artifacts
    - name: Download Build Artifacts for Testing From WinUser
      uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
      with: # note we always use binaries built on windows-2022.
        name: ${{ matrix.vec.config }}-windows-windows-2022-${{ matrix.vec.arch }}
        path: artifacts
    - name: Prepare Machine
      shell: pwsh
      run: scripts/prepare-machine.ps1 -ForTest -ForKernel
    - name: Test
      shell: pwsh
      timeout-minutes: 5
      run: scripts/test.ps1 -Config ${{ matrix.vec.config }} -Arch ${{ matrix.vec.arch }} -GHA -GenerateXmlResults -Kernel
    - name: Upload on Failure
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
      if: failure()
      with:
        name: BVT-Kernel-${{ matrix.vec.config }}-${{ matrix.vec.plat }}-${{ matrix.vec.os }}-${{ matrix.vec.arch }}
        path: artifacts

  Complete:
    name: Complete
    needs: [bvt, bvt-kernel]
    runs-on: ubuntu-latest
    steps:
    - run: echo "CI succeeded"
